version: '3'

services:
  db:
    image: postgres
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
        - ./db/psgl:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    restart: always

  web:
      build: .
      command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
      volumes:
          - .:/ki-ichi
          - gem_data:/usr/local/bundle
      ports:
          - 3000:3000
      depends_on:
          - db
      tty: true
      stdin_open: true

volumes:
  gem_data:
